int _putchar(char character);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(char character);
int _isalpha(char character);
int print_sign(int n);
int _abs(int n);
int print_last_digit(int n);
void jack_bauer(void);
void times_table(void);
int add(int a, int b);
